### ISSUE TITLE
Swift 2.3 version

### ISSUE THREAD

**Issue by pascalhow** [cbaker6/iOS-csr-swift#1]
Hi,

Just wondering if there are any plans to create a swift 2.3 version of this library.

Regards,
Pascal

**Comment by cbaker6** [comment]
Hi @pascalhow, I have created a 2.3 branch that compiles, but I'm unsure if it works. You will need to test to see if it works as there were a decent amount of code that converted from 3.0 to 2.3. The application I use to test is currently written in 3.0. Feel free to create test cases to contribute to this project for 2.3 and I can later convert them to 3.0.
